In [2]:
from sklearn.preprocessing import scale
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

### KNN Algorithm, Kmeans
* KNN 지도학습(회귀, 분류), KMeans 비지도학습

### K-means
* k개를 지정하여 평균을 통해 군집화
* 비지도학습이라는 것은 (정답을 준 것이 아니라) 정답이 없는 데이터에서 머신에게 패턴을 찾아달라고 하는 것
* y라벨이 없는 상태에서 데이터를 집어넣고 특성을 군집화
* 군집화는 같은 패턴끼리 묶는다.
* 거리의 기반으로 작동(유클리디안 거리)
* k-means의 k는 클러스터(군집)의 개수
* k값은 사용자가 지정하는 값
#### 단점
* 거리기반으로만 작동하기 때문에 거리가 55, 45의 비슷한 차이여도 55에 가깝게 하드클러스팅을 한다는 점에서 문제가 된다.
* 거리 기반이기 때문에 이상치에 민감하다.
* 단순히 거리기반의 평균으로 작동하기 때문에 그룹 자체의 분산 구조는 반영하지 못한다.
* 데이터의 양이 많기 때문에 반복 횟수가 많아지면 속도가 느려질 수 있다.
* 몇 개의 군집을 선택해야 하는지 지정해 주는 것이 어렵다.
#### 장점
* 군집화 과정에서 가장 많이 활용
* 이해가 쉬움
* 간결한 알고리즘(거리 기반 이해)

In [4]:
df=pd.read_csv('wine_test.csv')

In [6]:
df.columns

Index(['Unnamed: 0', 'alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash',
       'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'class'],
      dtype='object')

In [7]:
#column 정리
df= df[['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash',
       'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'class']]

In [9]:
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0
1,NaN,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,0
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,2
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,2
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,2
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,2
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,2

In [10]:
df['class'].value_counts()

1    71
0    59
2    48
Name: class, dtype: int64

### kmeans 사용 코드

In [13]:
kmeans=KMeans(n_clusters=3,init='k-means++', max_iter=300, random_state=111)

In [14]:
kmeans

KMeans(n_clusters=3, random_state=111)

In [15]:
df.isna().sum()

alcohol                         2
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            5
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
class                           0
dtype: int64

In [16]:
df.dropna(inplace=True)

C:\Temp\ipykernel_31624\1379821321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [17]:
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0
5,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,2
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,2
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,2
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,2
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,2

### kmeans train
* fit 안에 넣는다.
* 기존 class column과 비교해서 kmeans class를 제외한 다른 column으로 군집화를 진행 했을 때 kmeans의 경우가 더 잘 군집화 되었는지 확인

In [18]:
df.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'class'],
      dtype='object')

In [20]:
df_sp=df[['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline']]

df_sp
# class를 제외한 wine data

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
5,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [21]:
kmeans.fit(df_sp)

C:\Users\ros43\AppData\Roaming\Python\Python38\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

KMeans(n_clusters=3, random_state=111)

In [22]:
#실제로 군집화가 어떻게 되었는지 확인
print(kmeans.labels_)
#자동으로 군집화된 내용을 보여줌

[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 1 0 0
 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 2 1 2 2 1 2 2 1 1 2 2 0 1 2 2
 2 1 2 2 1 1 2 2 2 2 2 1 1 2 2 2 2 2 1 2 1 2 1 2 1 2 2 2 2 1 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 1 1 1 1 2 2 2 1 1 2 2 1 1 2 1 1 2 2 2 2 1 1
 1 2 1 1 1 2 1 2 1 1 2 1 1 1 1 2 2 1 1 1 1 1 2]

In [23]:
#cluster: 비지도학습으로 만든 column
df_sp['cluster']=kmeans.labels_

In [24]:
df_sp['class']=df['class']

In [25]:
df_sp

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,cluster,class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0,0
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0,0
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0,0
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1,0
5,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,1,2
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,1,2
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,1,2
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,1,2
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,2,2

In [28]:
df_sp.groupby(['class','cluster'])['proline'].count()

class  cluster
0      0          44
       1          13
1      0           1
       1          17
       2          48
2      1          29
       2          19
Name: proline, dtype: int64

### 확인 결과
* 기존 군집과 비교했을 때 결과값이 조금 다름을 알 수 있음.
* kmeans는 비지도학습이기 때문에 정답이 존재하지 않기 때문에 기존 class와 비교한 것.
* kmeans의 원리는 평균기반 거리이기 때문에 기존 class와 군집이 다르게 나올 수 있다.

In [29]:
df_sp.groupby(['class'])['proline'].count()

class
0    57
1    66
2    48
Name: proline, dtype: int64

In [30]:
df_sp.groupby(['cluster'])['proline'].count()

cluster
0    45
1    59
2    67
Name: proline, dtype: int64

* 해당 column은 차원이 10개가 넘는 고차원인 상태이다.
* 고차원 상태의 data로 거리기반으로 군집화함.
* 무작정 kmeans를 모든 column에 대해 진행하면 차원의 저주라고 하는 문제가 발생할 수 있음.
* column이 많아지면 고차원인 경우, 거리가 미세하게 바뀌거나 거의 바뀌지 않을 수 있다.-> 군집화가 제대로 이루어지지 않음.

#### 어떤 기준으로 군집화할 column을 정해야 하는가? 
* data 내 유의미한  변수 사용 ->분석가가 직접 column 선별 가능
* 기술적인 측면에서는 feature에 대한 중요성을 기반으로 칼럼을 추출할 수 있다.
##### -> 모든 column들을 kmeans에 사용하는 것은 잘못된 방향이다!

In [31]:
df_sp

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,cluster,class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0,0
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0,0
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0,0
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1,0
5,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,1,2
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,1,2
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,1,2
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,1,2
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,2,2

* 위 data의 columns 중 class별로 평균 비교
* 평균의 차이가 많이 나는 경우, 이상치가 있을 것이라고 판단 -> 해당 column은 제외, 평균이 비슷한 column들만 선택하여 kmeans 진행

#### 기존 class를  기반으로 각 column의 평균 차이로 컬럼 선별 후 다시 군집화 진행

In [33]:
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0
5,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,2
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,2
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,2
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,2
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,2

In [37]:
a=list(df.columns)
a

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline',
 'class']

In [38]:
for i in a:
  print('-----------------------------',i,'mean 비교')
  print(df.groupby(['class'])[i].mean())

----------------------------- alcohol mean 비교
class
0    13.735263
1    12.294242
2    13.153750
Name: alcohol, dtype: float64
----------------------------- malic_acid mean 비교
class
0    2.021228
1    1.932121
2    3.333750
Name: malic_acid, dtype: float64
----------------------------- ash mean 비교
class
0    2.466140
1    2.245606
2    2.437083
Name: ash, dtype: float64
----------------------------- alcalinity_of_ash mean 비교
class
0    17.192982
1    20.257576
2    21.416667
Name: alcalinity_of_ash, dtype: float64
----------------------------- magnesium mean 비교
class
0    106.614035
1     93.454545
2     99.312500
Name: magnesium, dtype: float64
----------------------------- total_phenols mean 비교
class
0    2.844211
1    2.254848
2    1.678750
Name: total_phenols, dtype: float64
----------------------------- flavanoids mean 비교
class
0    2.986316
1    2.089545
2    0.781458
Name: flavanoids, dtype: float64
----------------------------- nonflavanoid_phenols mean 비교
class
0    0.290526
1    0.365152
2    0.447500
Name: nonflavanoid_phenols, dtype: float64
----------------------------- proanthocyanins mean 비교
class
0    1.908772
1    1.612879
2    1.153542
Name: proanthocyanins, dtype: float64
----------------------------- color_intensity mean 비교
class
0    5.554211
1    3.111970
2    7.396250
Name: color_intensity, dtype: float64
----------------------------- hue mean 비교
class
0    1.061930
1    1.066515
2    0.682708
Name: hue, dtype: float64
----------------------------- od280/od315_of_diluted_wines mean 비교
class
0    3.158947
1    2.789394
2    1.683542
Name: od280/od315_of_diluted_wines, dtype: float64
----------------------------- proline mean 비교
class
0    1118.105263
1     509.090909
2     629.895833
Name: proline, dtype: float64
----------------------------- class mean 비교
class
0    0.0
1    1.0
2    2.0
Name: class, dtype: float64

##### 평균 차이가 많이 나지 않는다고 판단된 칼럼
##### 'alcohol', 'ash', 'nonflavanoid_phenols' ,'proanthocyanins' 선택

In [39]:
df_sp_1 = df[['alcohol', 'ash', 'nonflavanoid_phenols' ,'proanthocyanins']]

In [40]:
df_sp_1

     alcohol   ash  nonflavanoid_phenols  proanthocyanins
0      14.23  2.43                  0.28             2.29
2      13.16  2.67                  0.30             2.81
3      14.37  2.50                  0.24             2.18
4      13.24  2.87                  0.39             1.82
5      14.20  2.45                  0.34             1.97
..       ...   ...                   ...              ...
173    13.71  2.45                  0.52             1.06
174    13.40  2.48                  0.43             1.41
175    13.27  2.26                  0.43             1.35
176    13.17  2.37                  0.53             1.46
177    14.13  2.74                  0.56             1.35

[171 rows x 4 columns]

In [41]:
kmeans.fit(df_sp_1)

C:\Users\ros43\AppData\Roaming\Python\Python38\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

KMeans(n_clusters=3, random_state=111)

In [43]:
#군집화된 내용 확인
print(kmeans.labels_)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 2 1 1 1 1 1 1 1 1 2 2 2
 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 0 0 0 1 2 2 0 1 2 1 0 0 2
 0 0 0 0 0 0 2 0 2 0 0 0 0 0 0 2 0 0 0 0 0 0 0 2 0 0 0 2 0 0 0 2 0 0 0 0 0
 0 2 0 0 0 1 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 1 2
 2 1 2 1 1 2 2 2 2 2 2 1 2 1 2 2 2 1 2 2 2 2 1]

In [44]:
df_sp_1['cluster'] = kmeans.labels_

C:\Temp\ipykernel_31624\492630041.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sp_1['cluster'] = kmeans.labels_

In [45]:
df_sp_1.groupby(['cluster'])['ash'].count()

cluster
0    48
1    61
2    62
Name: ash, dtype: int64

#### 군집화를 통해 얻을 수 있는 insight?
* 군집이 형성된다-> 해당 군집에 따른 data의 pattern이 다를 것이다.
* 군집에 따른 다른 columns의 값의 분포
* 비지도학습이기 때문에 군집이 없는 상태였지만 비교대상으로 비교 class를 생성했었다.
* 흩어진 data 분포에서 군집화가 되었으면, 해당 군집에 대한 다른 column들의 data 특성으로 새로운 insight를 도출해낼 수 있다.

In [46]:
df_sp_1

     alcohol   ash  nonflavanoid_phenols  proanthocyanins  cluster
0      14.23  2.43                  0.28             2.29        1
2      13.16  2.67                  0.30             2.81        1
3      14.37  2.50                  0.24             2.18        1
4      13.24  2.87                  0.39             1.82        1
5      14.20  2.45                  0.34             1.97        1
..       ...   ...                   ...              ...      ...
173    13.71  2.45                  0.52             1.06        2
174    13.40  2.48                  0.43             1.41        2
175    13.27  2.26                  0.43             1.35        2
176    13.17  2.37                  0.53             1.46        2
177    14.13  2.74                  0.56             1.35        1

[171 rows x 5 columns]

##### kmeans는 거리를 기반으로 작동하기 때문에 값에 대한 차이에 민감할 것이다.
##### -> clustering 시 scaling 필요.

### scaling 진행

In [47]:
df_sp_1

     alcohol   ash  nonflavanoid_phenols  proanthocyanins  cluster
0      14.23  2.43                  0.28             2.29        1
2      13.16  2.67                  0.30             2.81        1
3      14.37  2.50                  0.24             2.18        1
4      13.24  2.87                  0.39             1.82        1
5      14.20  2.45                  0.34             1.97        1
..       ...   ...                   ...              ...      ...
173    13.71  2.45                  0.52             1.06        2
174    13.40  2.48                  0.43             1.41        2
175    13.27  2.26                  0.43             1.35        2
176    13.17  2.37                  0.53             1.46        2
177    14.13  2.74                  0.56             1.35        1

[171 rows x 5 columns]